Repository sted1994/whats-cookin, pull requests merged in 2022-04, with the labels that each got.

#18 Feature/add search by tag or name feature
  dist/index.html
  src/classes/RecipeCard.js
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#19 Build User class and methods and event listeners for nav bar tabs
  dist/index.html
  src/apiCalls.js
  src/classes/RecipeCard.js
  src/classes/User.js
  src/data/users.js
  src/scripts.js
  test/RecipeCard-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: enhancement

#20 Feature/connect user data to dom
  dist/index.html
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/images/delete.png
  src/scripts.js
  src/styles.css
Labels: bug

#21 Fix bug on saving duplicate favorite recipes
  src/classes/RecipeCard.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
Labels: enhancement

#22 Setup/integrate api
  src/apiCalls.js
  src/scripts.js
Labels: enhancement

#23 Fix bug that does not reset all recipes page after search
  src/classes/RecipeRepository.js
  src/scripts.js
Labels: bug, enhancement

#24 Fix bugs in the To Cook list and one bug from the fav list
  dist/images/beef.png
  dist/images/chicken.png
  dist/images/left-arrow.png
  dist/images/magnifying-glass.png
  dist/images/pork.png
  dist/images/right-arrow.png
  dist/images/thyme.png
  dist/images/turing-logo.png
  dist/images/vegitarian.png
  dist/index.html
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/data/ingredients.js
  src/data/recipes.js
  src/data/users.js
  src/scripts.js
  src/styles.css
Labels: bug, enhancement

#26 Add event listeners on fav and saved recipes to show card
  src/scripts.js
Labels: enhancement

#28 Refactor and add styling to buttons throughout page
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#29 Refactor and add consistency to styling
  src/styles.css
Labels: enhancement

#30 Refactor/refactor files
  src/classes/RecipeCard.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
  src/styles.css
  test/RecipeCard-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: enhancement

#31 Setup/organize files
  src/domUpdates.js
  src/scripts.js
Labels: bug

#34 Add Pantry class and method to calculate shopping list
  dist/index.html
  src/classes/Pantry.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
Labels: bug, enhancement

#36 Add tests to Pantry Class
  src/classes/Pantry.js
  src/classes/RecipeRepository.js
  test/Pantry-test.js
  test/RecipeCard-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: test

#38 Add a final refactor
  README.md
  dist/bundle.js
  dist/bundle.js.map
  dist/images/beef.png
  dist/images/chicken.png
  dist/images/delete.png
  dist/images/left-arrow.png
  dist/images/magnifying-glass.png
  dist/images/pork.png
  dist/images/right-arrow.png
  dist/images/thyme.png
  dist/images/vegitarian.png
  dist/index.html
  src/apiCalls.js
  src/classes/Pantry.js
  src/classes/RecipeCard.js
  src/classes/RecipeRepository.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
  test/Pantry-test.js
  test/RecipeCard-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: bug, enhancement
