Repository sted1994/whats-cookin, pull requests merged in 2022-03, with the labels that each got.

#11 Create basic structure in HTML and CSS
  dist/bundle.js
  dist/index.html
  src/images/thyme.jpeg
  src/styles.css
Labels: enhancement

#13 Add My Recipes page structure and styling
  dist/index.html
  src/styles.css
Labels: enhancement

#14 Feature/functionality of classes
  src/classes/RecipeCard.js
  src/classes/RecipeRepository.js
  src/data/ingredients.js
  src/data/recipes.js
  test/RecipeCard-test.js
  test/RecipeRepository-test.js
Labels: enhancement, question

#15 Import files to script.js
  dist/bundle.js
  dist/bundle.js.map
  dist/images/beef.png
  dist/images/chicken.png
  dist/images/left-arrow.png
  dist/images/magnifying-glass.png
  dist/images/pork.png
  dist/images/right-arrow.png
  dist/images/thyme.png
  dist/images/turing-logo.png
  dist/images/vegitarian.png
  dist/index.html
  src/classes/RecipeCard.js
  src/data/recipes.js
  src/images/beef.png
  src/images/chicken.png
  src/images/pork.png
  src/images/thyme.png
  src/images/vegitarian.png
  src/scripts.js
  src/styles.css
Labels: help wanted
